
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ATR BOOLEAN BOOLEAN CASE CASE CHAR COMENTARIO DEFINE DELIMITADOR DO DO ELSE ELSE FOR FOR ID IF IF LBRACKET LCHAVE LIBIMPORT LPAREN NUMERO OPA OPL RBRACKET RCHAVE RPAREN STRING SWITCH SWITCH TIPO TIPO TIPO TIPO TIPO TIPO WHILE WHILEprograma : lista_declaracoeslista_declaracoes : lista_declaracoes declaracao\n| declaracaodeclaracao : declaracao_variaveis\n| declaracao_funcao\n| declaracao_preprocessador\n| atribuicaodeclaracao_variaveis : tipo lista_variaveis DELIMITADORdeclaracao_funcao : tipo ID LPAREN parametros RPAREN blocodeclaracao_preprocessador : LIBIMPORT '<' ID '.' ID '>'tipo : TIPOlista_variaveis : lista_variaveis ',' ID\n| IDparametros : lista_parametros\n| vaziolista_parametros : lista_parametros ',' tipo ID\n| tipo IDbloco : LCHAVE lista_comandos RCHAVElista_comandos : lista_comandos comando\n| comandocomando : atribuicao\n| comando_condicional\n| comando_loop\n| blocoatribuicao : ID ATR expressao DELIMITADORcomando_condicional : IF LPAREN expressao RPAREN blococomando_loop : WHILE LPAREN expressao RPAREN blocoexpressao : expressao OPL expressao\n| expressao OPA expressao\n| LPAREN expressao RPAREN\n| ID\n| NUMEROvazio : "
    
_lr_action_items = {'LIBIMPORT':([0,2,3,4,5,6,7,12,17,30,42,45,55,],[10,10,-3,-4,-5,-6,-7,-2,-8,-25,-9,-10,-18,]),'ID':([0,2,3,4,5,6,7,8,11,12,15,16,17,18,22,26,30,31,32,34,42,43,44,45,46,47,48,49,50,51,55,56,57,58,63,64,],[9,9,-3,-4,-5,-6,-7,14,-11,-2,20,24,-8,25,20,35,-25,20,20,41,-9,9,54,-10,9,-20,-21,-22,-23,-24,-18,-19,20,20,-26,-27,]),'TIPO':([0,2,3,4,5,6,7,12,17,19,30,37,42,45,55,],[11,11,-3,-4,-5,-6,-7,-2,-8,11,-25,11,-9,-10,-18,]),'$end':([1,2,3,4,5,6,7,12,17,30,42,45,55,],[0,-1,-3,-4,-5,-6,-7,-2,-8,-25,-9,-10,-18,]),'ATR':([9,],[15,]),'<':([10,],[16,]),'DELIMITADOR':([13,14,20,21,23,25,38,39,40,],[17,-13,-31,30,-32,-12,-28,-29,-30,]),',':([13,14,25,28,35,54,],[18,-13,-12,37,-17,-16,]),'LPAREN':([14,15,22,31,32,52,53,57,58,],[19,22,22,22,22,57,58,22,22,]),'NUMERO':([15,22,31,32,57,58,],[23,23,23,23,23,23,]),'RPAREN':([19,20,23,27,28,29,33,35,38,39,40,54,59,60,],[-33,-31,-32,36,-14,-15,40,-17,-28,-29,-30,-16,61,62,]),'OPL':([20,21,23,33,38,39,40,59,60,],[-31,31,-32,31,31,31,-30,31,31,]),'OPA':([20,21,23,33,38,39,40,59,60,],[-31,32,-32,32,32,32,-30,32,32,]),'.':([24,],[34,]),'RCHAVE':([30,46,47,48,49,50,51,55,56,63,64,],[-25,55,-20,-21,-22,-23,-24,-18,-19,-26,-27,]),'IF':([30,43,46,47,48,49,50,51,55,56,63,64,],[-25,52,52,-20,-21,-22,-23,-24,-18,-19,-26,-27,]),'WHILE':([30,43,46,47,48,49,50,51,55,56,63,64,],[-25,53,53,-20,-21,-22,-23,-24,-18,-19,-26,-27,]),'LCHAVE':([30,36,43,46,47,48,49,50,51,55,56,61,62,63,64,],[-25,43,43,43,-20,-21,-22,-23,-24,-18,-19,43,43,-26,-27,]),'>':([41,],[45,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'lista_declaracoes':([0,],[2,]),'declaracao':([0,2,],[3,12,]),'declaracao_variaveis':([0,2,],[4,4,]),'declaracao_funcao':([0,2,],[5,5,]),'declaracao_preprocessador':([0,2,],[6,6,]),'atribuicao':([0,2,43,46,],[7,7,48,48,]),'tipo':([0,2,19,37,],[8,8,26,44,]),'lista_variaveis':([8,],[13,]),'expressao':([15,22,31,32,57,58,],[21,33,38,39,59,60,]),'parametros':([19,],[27,]),'lista_parametros':([19,],[28,]),'vazio':([19,],[29,]),'bloco':([36,43,46,61,62,],[42,51,51,63,64,]),'lista_comandos':([43,],[46,]),'comando':([43,46,],[47,56,]),'comando_condicional':([43,46,],[49,49,]),'comando_loop':([43,46,],[50,50,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> lista_declaracoes','programa',1,'p_programa','parser_testes.py',81),
  ('lista_declaracoes -> lista_declaracoes declaracao','lista_declaracoes',2,'p_lista_declaracoes','parser_testes.py',85),
  ('lista_declaracoes -> declaracao','lista_declaracoes',1,'p_lista_declaracoes','parser_testes.py',86),
  ('declaracao -> declaracao_variaveis','declaracao',1,'p_declaracao','parser_testes.py',90),
  ('declaracao -> declaracao_funcao','declaracao',1,'p_declaracao','parser_testes.py',91),
  ('declaracao -> declaracao_preprocessador','declaracao',1,'p_declaracao','parser_testes.py',92),
  ('declaracao -> atribuicao','declaracao',1,'p_declaracao','parser_testes.py',93),
  ('declaracao_variaveis -> tipo lista_variaveis DELIMITADOR','declaracao_variaveis',3,'p_declaracao_variaveis','parser_testes.py',97),
  ('declaracao_funcao -> tipo ID LPAREN parametros RPAREN bloco','declaracao_funcao',6,'p_declaracao_funcao','parser_testes.py',101),
  ('declaracao_preprocessador -> LIBIMPORT < ID . ID >','declaracao_preprocessador',6,'p_declaracao_preprocessador','parser_testes.py',105),
  ('tipo -> TIPO','tipo',1,'p_tipo','parser_testes.py',109),
  ('lista_variaveis -> lista_variaveis , ID','lista_variaveis',3,'p_lista_variaveis','parser_testes.py',113),
  ('lista_variaveis -> ID','lista_variaveis',1,'p_lista_variaveis','parser_testes.py',114),
  ('parametros -> lista_parametros','parametros',1,'p_parametros','parser_testes.py',118),
  ('parametros -> vazio','parametros',1,'p_parametros','parser_testes.py',119),
  ('lista_parametros -> lista_parametros , tipo ID','lista_parametros',4,'p_lista_parametros','parser_testes.py',123),
  ('lista_parametros -> tipo ID','lista_parametros',2,'p_lista_parametros','parser_testes.py',124),
  ('bloco -> LCHAVE lista_comandos RCHAVE','bloco',3,'p_bloco','parser_testes.py',128),
  ('lista_comandos -> lista_comandos comando','lista_comandos',2,'p_lista_comandos','parser_testes.py',132),
  ('lista_comandos -> comando','lista_comandos',1,'p_lista_comandos','parser_testes.py',133),
  ('comando -> atribuicao','comando',1,'p_comando','parser_testes.py',137),
  ('comando -> comando_condicional','comando',1,'p_comando','parser_testes.py',138),
  ('comando -> comando_loop','comando',1,'p_comando','parser_testes.py',139),
  ('comando -> bloco','comando',1,'p_comando','parser_testes.py',140),
  ('atribuicao -> ID ATR expressao DELIMITADOR','atribuicao',4,'p_atribuicao','parser_testes.py',144),
  ('comando_condicional -> IF LPAREN expressao RPAREN bloco','comando_condicional',5,'p_comando_condicional','parser_testes.py',148),
  ('comando_loop -> WHILE LPAREN expressao RPAREN bloco','comando_loop',5,'p_comando_loop','parser_testes.py',152),
  ('expressao -> expressao OPL expressao','expressao',3,'p_expressao','parser_testes.py',156),
  ('expressao -> expressao OPA expressao','expressao',3,'p_expressao','parser_testes.py',157),
  ('expressao -> LPAREN expressao RPAREN','expressao',3,'p_expressao','parser_testes.py',158),
  ('expressao -> ID','expressao',1,'p_expressao','parser_testes.py',159),
  ('expressao -> NUMERO','expressao',1,'p_expressao','parser_testes.py',160),
  ('vazio -> <empty>','vazio',0,'p_vazio','parser_testes.py',167),
]
